#!/usr/bin/env php
<?php
/**
* PHPCI - Continuous Integration for PHP
*
* @copyright    Copyright 2013, Block 8 Limited.
* @license      https://github.com/Block8/PHPCI/blob/master/LICENSE.md
* @link         http://www.phptesting.org/
*/

define('PHPCI_IS_CONSOLE', true);

require('bootstrap.php');

/** @var \Symfony\Component\Console\Application */
$application = $container->get('daemon.application');

$application->run(null, $container->get('console.output'));
