
<?php if(empty($builds) || !count($builds)): ?>
	<tr class="">
		<td colspan="6">No builds yet.</td>
	</tr>
<?php endif; ?>

<?php foreach($builds as $build): ?>
<?php
switch($build->getStatus())
{
	case 0:
		$cls = 'info';
		$status = 'Pending';
	break;

	case 1:
		$cls = 'warning';
		$status = 'Running';
	break;

	case 2:
		$cls = 'success';
		$status = 'Success';
	break;

	case 3:
		$cls = 'error';
		$status = 'Failed';
	break;
}
?>
<tr class="<?php print $cls; ?>">
	<td><a href="<?= PHPCI_URL ?>build/view/<?php print $build->getId(); ?>">#<?php print str_pad($build->getId(), 6, '0', STR_PAD_LEFT); ?></a></td>
	<td><a href="<?= PHPCI_URL ?>project/view/<?php print $build->getProjectId(); ?>"><?php print $build->getProject()->getTitle(); ?></a></td>
	<td><a href="<?php print $build->getCommitLink(); ?>"><?php print $build->getCommitId(); ?></a></td>
	<td><a href="<?php print $build->getBranchLink(); ?>"><?php print $build->getBranch(); ?></a></td>
	<td><?php print $status; ?></td>
	<td>
		<div class="btn-group">
			<a class="btn" href="<?= PHPCI_URL ?>build/view/<?php print $build->getId(); ?>">View</a>
			<?php if($this->User()->getIsAdmin()): ?>
			<button class="btn dropdown-toggle" data-toggle="dropdown">
				<span class="caret"></span>
			</button>
			<ul class="dropdown-menu">
				<li><a href="javascript:confirmDelete('<?= PHPCI_URL ?>build/delete/<?php print $build->getId(); ?>');">Delete Build</a></li>
			</ul>
			<?php endif; ?>
		</div>
	</td>
</tr>
<?php endforeach; ?>