<div id="title">
	<h1 style="display: inline-block">Dashboard</h1>
</div>
<div class="row">
	<div class="span3">
		<div class="well" style="padding: 8px 0">
		<ul class="nav nav-list">
			<li><a href="/"><i class="icon-home"></i> Dashboard</a></li>
			<li class="divider"></li>
			<li class="nav-header">Projects</li>

			<?php foreach($projects as $project): ?>
			<li><a href="/project/view/<?= $project->getId(); ?>"><i class="icon-folder-open"></i> <?= $project->getTitle(); ?></a></li>
			<?php endforeach; ?>
		</ul>
		</div>
	</div>
	<div class="span9">
		<table class="table table-striped table-bordered">
			<thead>
			<tr>
				<th>ID</th>
				<th>Project</th>
				<th>Commit</th>
				<th>Branch</th>
				<th>Status</th>
				<th style="width: 1%"></th>
			</tr>
			</thead>
			<tbody id="latest-builds">
				<?= $builds; ?>
			</tbody>
		</table>
	</div>
</div>

<script>
setInterval(function()
{
	$('#latest-builds').load('/index/latest');
}, 10000);
</script>