<html>
	<head>
		<title>PHPCI</title>

		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<link rel="stylesheet" type="text/css" href="/assets/css/bootstrap.min.css">
		<link rel="stylesheet" type="text/css" href="/assets/css/bootstrap-responsive.min.css">
		<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
		<script src="/assets/js/bootstrap.min.js"></script>

		<style>
			body
			{
				background: #246;
				padding-top: 70px;
			}

			#content
			{
				background: #fff;
				border: 10px solid #369;
				padding: 10px;
			}
		</style>
	</head>
	<body>
		<div class="navbar navbar-fixed-top">
			<div class="navbar-inner">
				<div class="container">
				<a class="brand" href="/">PHPCI</a>
				</div>
			</div>
		</div>

		<div id="content" class="container">
			<?= $content; ?>
		</div>
	</body>
</html>