<div id="title">
	<h1><?php print $type == 'add' ? 'Add Project' : 'Edit Project' ?></h1>
</div>

<div class="row">
	<div class="col-lg-4">
        <div class="panel panel-info">
            <div class="panel-body">
                <?php if(!is_null($key)): ?>
                    <p>To make it easier to get started, we've generated a public / private key pair for you to use for this project. To use it, just add the following public key to the "deploy keys" section of your repository settings on Github / Bitbucket.</p>

                    <textarea style="width: 90%; height: 150px;"><?php print $key ?></textarea>
                <?php elseif($type == 'add'): ?>
                    <p style="margin-bottom:0;">Fill in the form to the right to add your new project.</p>
                <?php else: ?>
                    <p style="margin-bottom:0;">Edit your project details using the form to the right.</p>
                <?php endif; ?>
            </div>
        </div>
	</div>
	<div class="col-lg-8">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Project Details</h3>
            </div>

            <div class="panel-body">
                <?php print $form; ?>
            </div>
        </div>
	</div>
</div>

<script>
window.return_url = <?php print json_encode((empty($_SERVER['HTTPS']) ? 'http' : 'https') . '://' . $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI']); ?>;

<?php
$gh = \b8\Config::getInstance()->get('phpci.github', null);

if($gh) {
	print 'window.github_app_id = ' . json_encode($gh['id']) . ';' . PHP_EOL;
}

if(!empty($token)) {
	print 'window.github_token = ' . json_encode($token) . ';' . PHP_EOL;
}
?>

$(document).ready(setupProjectForm);
</script>
