<div style="background: #900; padding: 25px;">
    <div style="background: #fff; padding: 15px; border-radius: 5px">
        <div style="font-family: arial, verdana, sans-serif; font-size: 25px; margin-bottom: 15px">
            <?= $project->getTitle(); ?> - Build #<?= $build->getId(); ?>
        </div>

        <div style="font-family: arial, verdana, sans-serif; font-size: 15px">
            <p>Your commit <strong><?= $build->getCommitId(); ?></strong> caused a failed build in project <strong><?= $project->getTitle(); ?></strong>.</p>

            <p>Please review <a href="<?= $build->getCommitLink(); ?>">your commit</a> and the <a href="<?= PHPCI_URL . 'build/view/' . $build->getId(); ?>">build log</a>.</p>
        </div>
    </div>
</div>