<?php use PHPCI\Helper\Lang; ?>

<div class="alert alert-danger">
    <p><strong>Adding requirements to the PHPCI composer.json file is no longer recommended as a method of installing your required testing tools.</strong><br>
        For this reason, we have removed the ability for PHPCI to modify the composer.json file for you.
        We recommend that you install testing tools using your project's own composer.json file, by adding them to the "require-dev" section of the file.</p>
</div>

<div class="row">
    <div class="col-md-6">
        <div class="box box-primary">
            <div class="box-header">
                <h3 class="box-title"><?php Lang::out('enabled_plugins'); ?></h3>
            </div>

            <table class="table">
                <thead>
                <tr>
                    <th><?php Lang::out('name'); ?></th>
                    <th><?php Lang::out('class'); ?></th>
                    <th><?php Lang::out('provided_by_package'); ?></th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($plugins as $plugin): ?>
                    <tr>
                        <td><?php print $plugin->name; ?></td>
                        <td><?php print $plugin->class; ?></td>
                        <td><?php print $plugin->source; ?></td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>

    <div class="col-md-6">
        <div class="box box-primary">
            <div class="box-header">
                <h3 class="box-title"><?php Lang::out('installed_packages'); ?></h3>
            </div>

            <table class="table">
                <thead>
                <tr>
                    <th><?php Lang::out('title'); ?></th>
                    <th><?php Lang::out('version'); ?></th>
                    <th width="1"></th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($installedPackages as $package => $version): ?>
                    <tr>
                        <td><?php echo $package; ?></td>
                        <td><?php echo $version; ?></td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>

    </div>
</div>

