<div id="title">
	<h1>Project: <?php print (is_object($project)) ? htmlspecialchars($project->getTitle()) : ' - '; ?></h1>
</div>

<div class="row">
	<div class="col-lg-3">
        <ul class="nav nav-pills nav-stacked">
			<li><a href="<?= PHPCI_URL ?>"><i class="icon-home"></i> Dashboard</a></li>
			<li><a href="<?= PHPCI_URL ?>project/view/<?php print $project->getId(); ?>"><i class="icon-folder-open"></i> <?php print htmlspecialchars($project->getTitle()); ?></a></li>
		</ul>
			<h5>Options</h5>
        <ul class="nav nav-pills nav-stacked">
			<li><a href="<?= PHPCI_URL ?>project/build/<?php print $project->getId(); ?>"><i class="icon-cog"></i> Build Now</a></li>

			<?php if($this->User()->getIsAdmin()): ?>
			<li><a href="<?= PHPCI_URL ?>project/edit/<?php print $project->getId(); ?>"><i class="icon-edit"></i> Edit Project</a></li>
			<li><a href="#" id="delete-project"><i class="icon-trash"></i> Delete Project</a></li>
			<?php endif; ?>
		</ul>

        <?php if (in_array($project->getType(), array('github', 'gitlab','bitbucket'))): ?>
            <br>
            <p class="alert alert-info">To automatically build this project when new commits are pushed, add the URL below
        <?php endif; ?>

			<?php
			switch($project->getType())
			{
				case 'github':
					$url	= (empty($_SERVER['HTTPS']) ? 'http' : 'https') . '://' . $_SERVER['HTTP_HOST'] . '/github/webhook/' . $project->getId();
					print ' as a "WebHook URL" in the <a href="https://github.com/' . $project->getReference() . '/settings/hooks">Service Hooks</a> section of your Github repository.<br><br><strong style="word-wrap: break-word;">' . $url . '</strong>';
				break;

				case 'gitlab':
					$url	= (empty($_SERVER['HTTPS']) ? 'http' : 'https') . '://' . $_SERVER['HTTP_HOST'] . '/gitlab/webhook/' . $project->getId();
					print ' as a "WebHook URL" in the Web Hooks section of your Gitlab repository.<br><br><strong style="word-wrap: break-word;">' . $url . '</strong>';
				break;

				case 'bitbucket':
					$url	= (empty($_SERVER['HTTPS']) ? 'http' : 'https') . '://' . $_SERVER['HTTP_HOST'] . '/bitbucket/webhook/' . $project->getId();
					print ' as a "POST" service in the <a href="https://bitbucket.org/' . $project->getReference() . '/admin/services">Services</a> section of your Bitbucket repository.<br><br><strong style="word-wrap: break-word;">' . $url . '</strong>';
				break;
			}
			?>
		</p>
	</div>
	<div class="col-lg-9">
		<table class="table table-striped table-bordered">
			<thead>
			<tr>
				<th>ID</th>
				<th>Project</th>
				<th>Commit</th>
				<th>Branch</th>
				<th>Status</th>
				<th style="width: 100px"></th>
			</tr>
			</thead>
			<tbody id="latest-builds">
				<?php print $builds; ?>
			</tbody>
		</table>

<?php

	print '<div><ul class="pagination">';
	$pages = ceil($total / 10);
	$pages = $pages == 0 ? 1 : $pages;

	print '<li class="'.($page == 1 ? 'disabled' : '').'"><a href="' . PHPCI_URL . 'project/view/'.$project->getId().'?p='.($page == 1 ? '1' : $page - 1).'">&laquo;</a></li>';

	for($i = 1; $i <= $pages; $i++)
	{
		print '<li><a href="' . PHPCI_URL . 'project/view/' . $project->getId() . '?p=' . $i . '">' . $i . '</a></li>';
	}

	print '<li class="'.($page == $pages ? 'disabled' : '').'"><a href="' . PHPCI_URL . 'project/view/'.$project->getId().'?p='.($page == $pages ? $pages : $page + 1).'">&raquo;</a></li>';

	print '</ul></div>';

?>
	</div>
</div>

<?php if($page == 1): ?>
<script>
    setInterval(function()
    {
        $('#latest-builds').load('<?= PHPCI_URL ?>project/builds/<?php print $project->getId(); ?>');
    }, 10000);

    $(function() {
        $('#delete-project').on('click', function (e) {
            e.preventDefault();
            confirmDelete("<?= PHPCI_URL ?>project/delete/<?php print $project->getId(); ?>");
        });
    })
</script>
<?php endif; ?>
